services:
  - type: web
    name: smart-study-planner
    env: python
    region: singapore  # Choose a region closest to you
    plan: free
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
